pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=0"
      - check-success=binary / unit-test (Debug)
      - check-success=binary / unit-test (Release)
      - check-success=Analyze (cpp)
    actions:
      merge:
        method: squash
