name: publish
on:
  schedule:
    - cron: '0 7 * * *'
  push:
    tags:
      - v*
jobs:
  publish-image:
    uses: ./.github/workflows/publish-image.yml
    secrets:
      registry: ghcr.io
      repository: ${{github.repository}}
      username: ${{github.repository_owner}}
      password: ${{secrets.GITHUB_TOKEN}}
