name: test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - uses: technote-space/get-diff-action@v6
        id: git-diff
        with:
          PATTERNS: |
            **/CMakeLists.txt
            **/*.(c,h)xx
      - uses: ./.github/workflows/test-build.yml
        if: ${{steps.git-diff.outputs.diff}}
